version: 2

updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-production:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - 'eslint*'
          - 'typescript*'
          - 'vitest'
          - '@playwright/*'

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /shared
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
